FROM node:22-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm config set registry https://registry.npmjs.org/ \
    && npm install --verbose

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]