name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: production
          tags: ${{ vars.DOCKER_USERNAME }}\/spiik.com:latest
      - name: Deploy to DigitalOcean Droplet
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_HUB_REPOSITORY: spiik.com
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $DROPLET_SSH_KEY $DROPLET_USER@$DROPLET_IP << 'EOF'
            docker login -u $DOCKER_HUB_USERNAME -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:latest
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d --name your_container_name -p your_host_port:your_container_port $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:latest
          EOF
