name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/spiik.com:latest
      - name: Deploy to DigitalOcean Droplet
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_HUB_REPOSITORY: spiik.com
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_SUDO_PASSWORD: ${{ secrets.DROPLET_SUDO_PASSWORD }}
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $DROPLET_USER@$DROPLET_IP << 'EOF'
            echo $DROPLET_SUDO_PASSWORD | sudo -S docker login -u $DOCKER_HUB_USERNAME --password-stdin <<< ${{ secrets.DOCKERHUB_TOKEN }}
            echo $DROPLET_SUDO_PASSWORD | sudo -S docker pull $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:latest
            echo $DROPLET_SUDO_PASSWORD | sudo -S docker stop your_container_name || true
            echo $DROPLET_SUDO_PASSWORD | sudo -S docker rm your_container_name || true
            echo $DROPLET_SUDO_PASSWORD | sudo -S docker run -d --name your_container_name -p your_host_port:your_container_port $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:latest
          EOF
